version: 2

jobs:
  build:
    docker:
      - image: ubuntu:16.04
    parallelism: 3
    resource_class: large
    working_directory: ~/wazn-stratum
    branches:
      only:
        - master
    steps:
      - run: |
          apt-get -qq update
          apt-get install -y -qq libboost-all-dev curl cmake build-essential libssl-dev git-core libzmq3-dev libsodium-dev
          curl -O https://dl.google.com/go/go1.11.1.linux-amd64.tar.gz && tar xzvf go1.11.1.linux-amd64.tar.gz
          echo 'export PATH=~/go/bin:$PATH' >> ~/.bashrc
      - restore_cache:
          keys:
            - v1-wazn-{{ arch }}.tar.gz
      - run: |
          git clone --recursive --depth 1 https://github.com/project-wazn/wazn.git ~/wazn
          pushd ~/wazn && cmake -DBUILD_SHARED_LIBS=1 . && make && popd
      - save_cache:
          key: v1-wazn-{{ arch }}.tar.gz
          paths:
            - ~/wazn
      - checkout
      - run:
          name: Compile
          environment:
            - WAZN_DIR: "~/wazn"
          command: |
            cmake .
            make
      - run:
          name: Test
          command: build/env.sh go test -v ./...
